import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { API_BASE } from './apiConfig';
import { authHeaders, useAuth } from './AuthContext';
type Page={url:string;revoked:boolean;requests:{id:string;status:string;scheduled_at:string;rep_name:string;availability:string}[]};
function ActionIcon({kind}:{kind:'copy'|'sms'|'revoke'|'restore'}){return <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">{kind==='copy'?<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/></>:kind==='sms'?<path d="M4 3h16v13H9l-5 5V3Z M8 7h8M8 11h6"/>:kind==='restore'?<><path d="M3 10a9 9 0 1 1 2 8M3 4v6h6"/><path d="m9 13 2 2 4-4"/></>:<><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></>}</svg>}
export default function CustomerPageControls({leadId,section='meeting'}:{leadId:string;section?:'links'|'files'|'meeting'}){
 const {token}=useAuth();const [data,setData]=useState<Page>(),[files,setFiles]=useState<{id:string;name:string;status:string}[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const base=`${API_BASE}/api/leads/${leadId}/customer-page`;
 useEffect(()=>{const controller=new AbortController();async function load(){try{const r=await fetch(base+(section==='files'?'/sync-status':''),{headers:authHeaders(token),signal:controller.signal});if(!r.ok)return;const d=await r.json();if(section==='files')setFiles(d.files);else setData(d);}catch{ /* Aborted or temporarily unavailable. */ }}void load();const timer=setInterval(()=>void load(),15000);return()=>{controller.abort();clearInterval(timer);};},[base,token,section]);
 async function act(action:'sms'|'revoke'){setBusy(true);setNotice('');try{const r=await fetch(base+(action==='sms'?'/sms':''),{method:action==='sms'?'POST':'PATCH',headers:{...authHeaders(token),'Content-Type':'application/json'},body:action==='revoke'?JSON.stringify({revoke:!data?.revoked}):undefined});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Could not complete action');if(action==='revoke')setData(prev=>prev?{...prev,revoked:!prev.revoked}:prev);setNotice(action==='sms'?'SMS sent.':'Access updated.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 if(section==='files')return files.length?<div className="ls-files">{files.map(file=><article key={file.id}><span className="ls-file-icon">File</span><div className="ls-file-content"><strong>{file.name}</strong><small>Uploaded by customer</small></div><span className="ls-success" aria-label="Saved">&#10003;</span></article>)}</div>:null;
 if(!data)return null;
 if(section==='links')return <><div className="ls-link"><div><strong>Customer link{data.revoked?' (revoked)':''}</strong><span title={data.url}>{data.url}</span></div><button title="Copy customer link" aria-label="Copy customer link" onClick={()=>void navigator.clipboard.writeText(data.url).then(()=>setNotice('Link copied.')).catch(()=>setNotice('Could not copy link.'))}><ActionIcon kind="copy"/></button><button title="Send SMS" aria-label="Send customer link by SMS" disabled={busy||data.revoked} onClick={()=>void act('sms')}><ActionIcon kind="sms"/></button><button title={data.revoked?'Restore access':'Revoke access'} aria-label={data.revoked?'Restore customer access':'Revoke customer access'} disabled={busy} onClick={()=>void act('revoke')}><ActionIcon kind={data.revoked?"restore":"revoke"}/></button></div>{notice&&<p role="status">{notice}</p>}</>;
 const meeting=data.requests[0];return <section className="ls-card"><h3>Scheduled walkthrough</h3>{meeting?<p>{meeting.scheduled_at&&<>{new Date(meeting.scheduled_at).toLocaleString('en-US')} | </>}{meeting.rep_name&&<>{meeting.rep_name} | </>}<strong>{({scheduled:'Approved',requested:'Requested',completed:'Completed',cancelled:'Cancelled'} as Record<string,string>)[meeting.status]||meeting.status}</strong></p>:<p>No walkthrough requested</p>}<Link to={`/walkthrough-requests?lead_id=${encodeURIComponent(leadId)}`}>Meeting Calendar</Link></section>;
}
