import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { API_BASE } from "./apiConfig";
import { authHeaders, useAuth } from "./AuthContext";
import CustomerPageControls from "./CustomerPageControls";

type Meeting={created_at?:string;id:string;status:string;availability:string;timezone:string;scheduled_at:string|null;assigned_to:string};
type Row={lead_id:string;name:string;company:string;company_id:string;requests:Meeting[]};
export default function WalkthroughRequestsPage(){const {token}=useAuth();const [rows,setRows]=useState<Row[]>([]),[reps,setReps]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState('requested'),[company,setCompany]=useState(''),[repFilter,setRepFilter]=useState(''),[search,setSearch]=useState(''),[active,setActive]=useState(''),[dateFilter,setDateFilter]=useState('');
const load=useCallback(async()=>{const r=await fetch(`${API_BASE}/api/walkthrough-requests`,{headers:authHeaders(token)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Could not load requests');setRows(d.items);setReps(d.reps);},[token]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
return <main style={{padding:24,width:'100%',maxWidth:1400,margin:'0 auto'}}><h1>Live call requests &amp; scheduling</h1><div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}><select aria-label="Request status" value={filter} onChange={e=>setFilter(e.target.value)}>{['requested','scheduled','completed','cancelled','all','unassigned'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Company" value={company} onChange={e=>setCompany(e.target.value)}><option value="">All companies</option>{Array.from(new Map(rows.map(r=>[r.company_id,r.company])).entries()).map(([id,name])=><option key={id} value={id||'__none__'}>{name}</option>)}</select><select aria-label="Rep" value={repFilter} onChange={e=>setRepFilter(e.target.value)}><option value="">All reps</option>{reps.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input type="date" aria-label="Request or appointment date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/><input placeholder="Search customer" aria-label="Search customer" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>void load().catch(e=>setError(e.message))}>Refresh</button></div>{error&&<p role="alert">{error}</p>}
{rows.filter(r=>(!company||(r.company_id||'__none__')===company)&&r.name.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='unassigned'?!r.company_id:r.requests.some(m=>m.status===filter)))&&(!repFilter||r.requests.some(m=>m.assigned_to===repFilter))&&(!dateFilter||r.requests.some(m=>{const d=m.scheduled_at||m.created_at;return d&&new Date(d).toLocaleDateString('en-CA')===dateFilter;}))).map(row=><section key={row.lead_id} style={{background:'white',padding:18,border:'1px solid #d8dde6',borderRadius:8,marginBottom:15}}><div style={{display:'flex',justifyContent:'space-between'}}><div><Link to={`/leads/${row.lead_id}`} target="_blank" rel="noopener noreferrer"><strong>{row.name}</strong></Link><p>{row.company}</p></div><button onClick={()=>setActive(active===row.lead_id?'':row.lead_id)}>Manage customer page / company</button></div>{active===row.lead_id&&<CustomerPageControls leadId={row.lead_id}/>}{row.requests.filter(m=>(filter==='all'||filter==='unassigned'||m.status===filter)&&(!repFilter||m.assigned_to===repFilter)).map(m=><Schedule key={`${m.id}-${m.status}-${m.scheduled_at}`} meeting={m} reps={reps} onSave={load}/>)}</section>)}</main>;}
function Schedule({meeting,reps,onSave}:{meeting:Meeting;reps:{id:string;name:string}[];onSave:()=>Promise<void>}){const {token}=useAuth();const [rep,setRep]=useState(meeting.assigned_to),[date,setDate]=useState(()=>{if(!meeting.scheduled_at)return '';const d=new Date(meeting.scheduled_at);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}),[status,setStatus]=useState(meeting.status),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(){setBusy(true);setError('');try{const r=await fetch(`${API_BASE}/api/walkthrough-requests/${meeting.id}`,{method:'PATCH',headers:{...authHeaders(token),'Content-Type':'application/json'},body:JSON.stringify({status,assigned_to:rep||null,scheduled_at:date?new Date(date).toISOString():null})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Could not schedule');await onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <div style={{borderTop:'1px solid #eee',paddingTop:12}}><p>Customer availability: {meeting.availability} ({meeting.timezone})</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><select aria-label="Assigned rep" value={rep} onChange={e=>setRep(e.target.value)}><option value="">Choose rep</option>{reps.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><label>Appointment (your local time)<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{['requested','scheduled','completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select><button disabled={busy} onClick={()=>void save()}>Save</button></div>{error&&<p role="alert">{error}</p>}</div>;}
